version: '3.4'

services:
  restapi:
    image: ${DOCKER_REGISTRY-}restapi
    depends_on:
      - "db"
      - "redis"
    build:
      context: .
      dockerfile: src/RestApi/Dockerfile
    environment:
      - ConnectionStrings__DefaultConnection=User ID=postgres;Password=postgres;Server=local_pgdb;Port=5432;Database=postgres;IntegratedSecurity=true;Pooling=true;
  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

  db:
    image: postgres:latest
    container_name: local_pgdb
    restart: always
    ports:
      - "54320:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      #- ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - local_pgdata:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: gevorgdannielyan@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  local_pgdata:
  pgadmin-data:
